pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'mongo-express'
                    args '-p 3005:3005'
                }
            }
            steps {
                sh 'npm install'
                echo 'finished build'
            }
        }
        stage('Tests') {
            agent {
                docker {
                    image 'mongo-express'
                    args '-p 3005:3005'
                }
            }
            steps {
                sh 'npm run test'
                echo 'Finished Tests'
            }
        }
    }
}